### ISSUE TITLE
The weathermapper configuration directory is not writable

### ISSUE THREAD

**Issue by pedjaj** [pblasquez/weathermapper#11]
if you get 
`The weathermapper configuration directory is not writable! You should try running "chown -R apache:apache /opt/weathermapper/conf.d" `
and chown -R apache:apache /opt/weathermapper/conf.d not working
you can tray (centos7 and apache)

`chcon -R -t httpd_sys_content_rw_t /opt/weathermapper/conf.d`

**Comment by MarkProminic** [comment]
I disabled SELINUX and used the command that was specified on the error page and this worked for me. I believe this to be a SELINUX issue.

**Comment by pblasquez** [comment]
Thanks for returning and updating.
