### ISSUE TITLE
Node names and Labels identical across all devices

### ISSUE THREAD

**Issue by bdg-robert** [pblasquez/weathermapper#5]
I'm attempting to generate a map based on my routers, however when the file is generated two odd things are happening:

First, I receive these warnings:
```
PHP Warning:  Illegal string offset 'rrdcached' in /opt/weathermapper/weathermapper.php on line 61
PHP Warning:  Illegal string offset 'rrdcached_dir' in /opt/weathermapper/weathermapper.php on line 61
```

Second, in the weathermap.conf file that is generated, I see the following throughout the config:
```
# regular NODEs:
NODE 10.2
     LABEL 10.2
     INFOURL /device/device=353/
     OVERLIBGRAPH /graph.php?height=100&width=512&device=353&type=device_bits&legend=no
     ICON 80 80 images/Router.png
     LABELOFFSET 0 10
     POSITION 6400 250

NODE 10.2
     LABEL 10.2
     INFOURL /device/device=396/
     OVERLIBGRAPH /graph.php?height=100&width=512&device=396&type=device_bits&legend=no
     ICON 80 80 images/Router.png
     LABELOFFSET 0 10
     POSITION 6600 250

NODE 10.2
     LABEL 10.2
     INFOURL /device/device=392/
     OVERLIBGRAPH /graph.php?height=100&width=512&device=392&type=device_bits&legend=no
     ICON 80 80 images/Router.png
     LABELOFFSET 0 10
     POSITION 6200 250

NODE 10.2
     LABEL 10.2
     INFOURL /device/device=99/
     OVERLIBGRAPH /graph.php?height=100&width=512&device=99&type=device_bits&legend=no
     ICON 80 80 images/Router.png
     LABELOFFSET 0 10
     POSITION 6800 250
```

Any idea why this may be occurring? It's completely possible I'm messing up somewhere. :(

**Comment by barryodonovan** [comment]
@bdg-robert 

I've made the following change in weathermapper.php 
```
// Concatenate link configs
$config .= create_link_config($links,'127.0.0.1:42217','');
// $config .= create_link_config($links,$CONFIG['rrdcached'],$config['rrdcached_dir']);
```
and this appears to resolve the issue with rrdcached (at least I get a map conf created sucessfully)

**Comment by bdg-robert** [comment]
I'm not so sure the warnings are the problem; it may be because I don't use hostnames, but instead IPs? Most, if not all, of my routers first two octets are "10.2" so I think it has something to do with the way it obtains that information from LibreNMS.

I'll give it a shot, though.

**Comment by barryodonovan** [comment]
Ah, you could be onto something there. Weathermapper failed to generate any config on my system due to the errors.

**Comment by bdg-robert** [comment]
That did alleviate the warnings, but the issue with the resulting map file persists.

**Comment by bdg-robert** [comment]
I found a function in the include called shortname() that I was able to modify to keep from trimming the IPs down to the first two octets. Hopefully there's a more elegant fix than this.

**Comment by pblasquez** [comment]
Hi, thanks for reporting this!

I have committed a change that fix these issues, if you could test and report back I would appreciate it, thanks!

**Comment by bdg-robert** [comment]
Will get this tested tomorrow, thanks!

**Comment by pblasquez** [comment]
Hi, no news is good news I hope?

**Comment by kkrumm1** [comment]
Everything seems to working fine on my end. :)

**Comment by pblasquez** [comment]
Great! I will close, please feel free to open a new issue if this isn't fully fixed.

**Comment by bdg-robert** [comment]
Hey, Paul. Sorry, I haven't had any time to look into this again. I'll open another issue if I see any problems when I can circle back to this.
