### ISSUE TITLE
Weathermapper and links between nodes

### ISSUE THREAD

**Issue by ArtemKabanov** [pblasquez/weathermapper#9]
Hi, I have installed weathermap and weathermapper plugin.
I would like weathermapper to draw links between the nodes by the decription on ports.
For example, on switches i have two links or more(uplinks and downlinks) with description “uplink-switch-<hostname>” and “downlink-switch-<hostname>”. How can i do this?

**Comment by pblasquez** [comment]
Sorry, there is a dependency on LibreNMS discovery to build the relationships between devices right now.  We could possibly add a filter to only include links that match a regex, but it would still be based on the LibreNMS database structure.

Are you just looking to filter links?

**Comment by ArtemKabanov** [comment]
I have some L2 segment with 500+ devices. Links between devices have descriptions. Descriptions are formed by some mask(regex). And i'm looking for some instrument to draw L2 map based on description.

**Comment by pblasquez** [comment]
Yes, this plugin doesn't do the discovery, just the map layout.  You would need another form of autodiscovery to populate the LibreNMS device relationship tables, then you could use this plugin.

Closing this as out of scope.
